#pragma once

const QString OF_BASE_BACKGROUND_COLOR = "#e0dbd5";

const QString OF_MODULE_UI_MANAGER = "UIMANAGER";
const QString OF_MODULE_CHARACTER  = "CHARACTER";
const QString OF_MODULE_SIMULATOR  = "SIMULATOR";
